name: kost_go
description: "Tugas Besar Pemrograman Mobile - Aplikasi Pencarian Kost"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Menggunakan rentang SDK yang aman untuk kebanyakan versi Flutter

dependencies:
  flutter:
    sdk: flutter

  # --- UTK ANGGOTA 1 (Core & Network) ---
  http: ^1.2.0          # Menggunakan versi stabil untuk request API

  # --- UTK ANGGOTA 3 & 4 (State Management) ---
  provider: ^6.1.2      # State management untuk mengatur logika bisnis

  # --- UTK ANGGOTA 3 (Maps & Lokasi) ---
  google_maps_flutter: ^2.17.0  # Untuk menampilkan Google Maps
  geolocator: ^11.0.0          # Untuk mengambil GPS HP Pengguna

  # TAMBAHKAN DUA BARIS INI:
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
     - assets/images/